//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaptopInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaptopInfo()
        {
            this.OrderInfoes = new HashSet<OrderInfo>();
        }
    
        public int LaptopID { get; set; }
        public string Brand { get; set; }
        public string Processor { get; set; }
        public string RAM { get; set; }
        public int Price { get; set; }
        public string Model { get; set; }
        public string imgAddr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInfo> OrderInfoes { get; set; }
    }
}
