//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int OrderID { get; set; }
        public int LaptopID { get; set; }
        public string CustomerID { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual LaptopInfo LaptopInfo { get; set; }
    }
}
